# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from trade.v1 import trading_pb2 as trade_dot_v1_dot_trading__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in trade/v1/trading_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTrade = channel.unary_unary(
                '/trade.v1.TradeService/CreateTrade',
                request_serializer=trade_dot_v1_dot_trading__pb2.CreateTradeRequest.SerializeToString,
                response_deserializer=trade_dot_v1_dot_trading__pb2.CreateTradeResponse.FromString,
                _registered_method=True)
        self.GetTrade = channel.unary_unary(
                '/trade.v1.TradeService/GetTrade',
                request_serializer=trade_dot_v1_dot_trading__pb2.GetTradeRequest.SerializeToString,
                response_deserializer=trade_dot_v1_dot_trading__pb2.GetTradeResponse.FromString,
                _registered_method=True)
        self.DeleteTrade = channel.unary_unary(
                '/trade.v1.TradeService/DeleteTrade',
                request_serializer=trade_dot_v1_dot_trading__pb2.DeleteTradeRequest.SerializeToString,
                response_deserializer=trade_dot_v1_dot_trading__pb2.DeleteTradeResponse.FromString,
                _registered_method=True)
        self.GetWalletBalance = channel.unary_unary(
                '/trade.v1.TradeService/GetWalletBalance',
                request_serializer=trade_dot_v1_dot_trading__pb2.GetWalletBalanceRequest.SerializeToString,
                response_deserializer=trade_dot_v1_dot_trading__pb2.GetWalletBalanceResponse.FromString,
                _registered_method=True)
        self.AddFunds = channel.unary_unary(
                '/trade.v1.TradeService/AddFunds',
                request_serializer=trade_dot_v1_dot_trading__pb2.AddFundsRequest.SerializeToString,
                response_deserializer=trade_dot_v1_dot_trading__pb2.AddFundsResponse.FromString,
                _registered_method=True)


class TradeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWalletBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFunds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTrade,
                    request_deserializer=trade_dot_v1_dot_trading__pb2.CreateTradeRequest.FromString,
                    response_serializer=trade_dot_v1_dot_trading__pb2.CreateTradeResponse.SerializeToString,
            ),
            'GetTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrade,
                    request_deserializer=trade_dot_v1_dot_trading__pb2.GetTradeRequest.FromString,
                    response_serializer=trade_dot_v1_dot_trading__pb2.GetTradeResponse.SerializeToString,
            ),
            'DeleteTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTrade,
                    request_deserializer=trade_dot_v1_dot_trading__pb2.DeleteTradeRequest.FromString,
                    response_serializer=trade_dot_v1_dot_trading__pb2.DeleteTradeResponse.SerializeToString,
            ),
            'GetWalletBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWalletBalance,
                    request_deserializer=trade_dot_v1_dot_trading__pb2.GetWalletBalanceRequest.FromString,
                    response_serializer=trade_dot_v1_dot_trading__pb2.GetWalletBalanceResponse.SerializeToString,
            ),
            'AddFunds': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFunds,
                    request_deserializer=trade_dot_v1_dot_trading__pb2.AddFundsRequest.FromString,
                    response_serializer=trade_dot_v1_dot_trading__pb2.AddFundsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trade.v1.TradeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trade.v1.TradeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade.v1.TradeService/CreateTrade',
            trade_dot_v1_dot_trading__pb2.CreateTradeRequest.SerializeToString,
            trade_dot_v1_dot_trading__pb2.CreateTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade.v1.TradeService/GetTrade',
            trade_dot_v1_dot_trading__pb2.GetTradeRequest.SerializeToString,
            trade_dot_v1_dot_trading__pb2.GetTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade.v1.TradeService/DeleteTrade',
            trade_dot_v1_dot_trading__pb2.DeleteTradeRequest.SerializeToString,
            trade_dot_v1_dot_trading__pb2.DeleteTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWalletBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade.v1.TradeService/GetWalletBalance',
            trade_dot_v1_dot_trading__pb2.GetWalletBalanceRequest.SerializeToString,
            trade_dot_v1_dot_trading__pb2.GetWalletBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFunds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade.v1.TradeService/AddFunds',
            trade_dot_v1_dot_trading__pb2.AddFundsRequest.SerializeToString,
            trade_dot_v1_dot_trading__pb2.AddFundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
