# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth/v1/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth/v1/auth.proto\x12\x07\x61uth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n\x05Token\x12-\n\tcreate_ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\texpire_ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05token\x18\x03 \x01(\t\"x\n\x04User\x12\x0c\n\x04uuid\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x1d\n\x05token\x18\x03 \x01(\x0b\x32\x0e.auth.v1.Token\x12\x31\n\rcreation_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"[\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\"\x9c\x01\n\x12\x43reateUserResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".auth.v1.CreateUserResponse.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\"A\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x10\n\x0cSTATUS_ERROR\x10\x01\x12\r\n\tSTATUS_OK\x10\x02\"3\n\x10LoginUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\xaf\x01\n\x11LoginUserResponse\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.auth.v1.LoginUserResponse.Status\x12\x1b\n\x04user\x18\x02 \x01(\x0b\x32\r.auth.v1.User\"J\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15STATUS_BAD_LOGIN_INFO\x10\x01\x12\r\n\tSTATUS_OK\x10\x02\x32\xa1\x01\n\x14\x41uthorizationService\x12\x45\n\nCreateUser\x12\x1a.auth.v1.CreateUserRequest\x1a\x1b.auth.v1.CreateUserResponse\x12\x42\n\tLoginUser\x12\x19.auth.v1.LoginUserRequest\x1a\x1a.auth.v1.LoginUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKEN']._serialized_start=64
  _globals['_TOKEN']._serialized_end=180
  _globals['_USER']._serialized_start=182
  _globals['_USER']._serialized_end=302
  _globals['_CREATEUSERREQUEST']._serialized_start=304
  _globals['_CREATEUSERREQUEST']._serialized_end=395
  _globals['_CREATEUSERRESPONSE']._serialized_start=398
  _globals['_CREATEUSERRESPONSE']._serialized_end=554
  _globals['_CREATEUSERRESPONSE_STATUS']._serialized_start=489
  _globals['_CREATEUSERRESPONSE_STATUS']._serialized_end=554
  _globals['_LOGINUSERREQUEST']._serialized_start=556
  _globals['_LOGINUSERREQUEST']._serialized_end=607
  _globals['_LOGINUSERRESPONSE']._serialized_start=610
  _globals['_LOGINUSERRESPONSE']._serialized_end=785
  _globals['_LOGINUSERRESPONSE_STATUS']._serialized_start=711
  _globals['_LOGINUSERRESPONSE_STATUS']._serialized_end=785
  _globals['_AUTHORIZATIONSERVICE']._serialized_start=788
  _globals['_AUTHORIZATIONSERVICE']._serialized_end=949
# @@protoc_insertion_point(module_scope)
